### ISSUE TITLE
Project를 닫은 후 다시 이미지를 불러올 시 오류 발생

### ISSUE THREAD

**Issue by tuna1210** [diskhkme/Godot_PNID_Viewer#1]
image를 열고 xml을 불러와 작업한 뒤 Project를 닫는 경우, 이후 다시 이미지를 불러올 시 프로세스가 강제종료 됨

**Comment by diskhkme** [comment]
d816162d08eba7a25667d0ca696fb2b3a96d52a2 에서 수정됨
