### ISSUE TITLE
[Feature] 우클릭으로 화면 이동 시 심볼 선택 방지

### ISSUE THREAD

**Issue by tuna1210** [diskhkme/Godot_PNID_Viewer#2]
현재 우클릭으로 드래그 하면서 도면을 이동하면 심볼이 클릭되어 화면이 이상하게 전환되는 현상이 있습니다. (특히 큰 심볼 근처에서) 
우클릭으로 이동할 때는 심볼이 클릭되지 않으면 좋을 것 같습니다.

**Comment by diskhkme** [comment]
ca254f341f93b929625cf1b91d91bc1866192d61 에서 수정했습니다.
